### ISSUE TITLE
Addon changes language to english

### ISSUE THREAD

**Issue by killerpommes** [shroudedcode/refined-prime-video#11]
Hi, thanks for this addon.
I got a problem, this addon changes the language of amazon to english.

I hope you can do something about that. 

greetings

**Comment by niklashigi** [comment]
I can confirm this issue and I already know what the cause is: When Refined Prime Video fetches a user's "storefront" (basically the Prime Video homepage) to assemble the "Continue watching" list, it [includes the query parameter `language=en`](https://github.com/shroudedcode/refined-prime-video/blob/15087d0711357418300cf37f27b529aaf8b7c38d/source/libs/fetch-my-videos.ts#L33). This results in the playback actions (those "Play S1 E2" buttons you can click on after hovering over something on the storefront) to always have English labels.

I thought this would be a good idea because it prevents any issues that could possible arise from a language that somehow shows the season and episode numbers in a different way. The problem with this is that Prime Video will change the user's selected language to English as a side effect by updating a cookie.

There's two ways to fix this I can think of:

- Preventing Amazon from changing the language by resetting the relevant cookie after the request or by preventing it from changing it in the first place. No matter how I implement this I'd probably have to add more required permissions to RPV which I want to avoid.

- Stop forcing the language to English and change [the parsing code](https://github.com/shroudedcode/refined-prime-video/blob/15087d0711357418300cf37f27b529aaf8b7c38d/source/libs/fetch-my-videos.ts#L90) to just find any two numbers in the label. This change would be a lot easier, but I'd have to do a good amount of testing with different languages to make sure this doesn't cause any issues for anyone.

I'll probably look into the second option and try to implement a fix. Thanks for reporting this!
