### ISSUE TITLE
Feature request: "hide movies"

### ISSUE THREAD

**Issue by boxabirds** [shroudedcode/refined-prime-video#9]
Cool extension! I wondered what would be involved to have a simple hack that gave users the option to hide movies. I'm tired of it showing me movies I've already seen. It could be initially a localstorage thing. I had a quick look at the HTML and inside the list item is an aria tag that could be used. Keying by name is probably good enough for this simple hack. Then later, you could offer a way to save it in the cloud or something.

**Comment by niklashigi** [comment]
> Cool extension!

Thanks, Julian, I'm glad you like it!

> I wondered what would be involved to have a simple hack that gave users the option to hide movies.

This is totally possible, but it would be more than a "simple hack" since I only want to ship polished features with this extension. Making this a polished feature would, in my opinion, entail:

- Adding a "Hide" button to movie hover cards that nicely blends into the user interface (maybe next to the "Add season to watchlist" icon).

- Keeping track of hidden movies and syncing them between devices.
  - This is the easiest part since [`storage.sync`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) (which I'm already using for settings) automatically syncs data between browsers with the same Google/Firefox/etc. account.

- Actually hiding selected movies from storefront pages.
  - This one's a bit more tricky because Amazon loads in more movies when the user scrolls down. Those newly added movies also have to be filtered based on the list of hidden movies, so a [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) will have to be used.

- Allowing users to remove movies from the list of hidden movies.
  - This might not seem like a hugely important feature, but I really hate apps that make it difficult or impossible you to undo something you've done, so there should be some way to list and remove hidden movies.

Considering all of this, I am not sure if the effort of implementing and maintaining this feature is worth it. This doesn't mean I'm against it, but I'm not considering it a priority at the moment. If you wanna give this a shot yourself, go ahead, though, I'm open to pull requests!

> I had a quick look at the HTML and inside the list item is an aria tag that could be used.

In case you do want to implement this yourself, here's a tip regarding this: You can extract a movie's ASIN (number Amazon uses to identify products and also movies) from the link URL (for example using a RegEx like this: `/[A-Z0-9]{10}/`) and use that as a key.

**Comment by niklashigi** [comment]
It seems like Amazon itself has implemented this feature now:

![](https://user-images.githubusercontent.com/29176678/92454605-f84c8280-f1c0-11ea-86df-c3a7df11e275.png)

There's now a "Hide this season" button on series and a "Hide this movie" button on movies.
With this feature available natively, there's no longer a need for Refined Prime Video to add this, so I'm closing this issue.
